### ISSUE TITLE
1.9 update, new enderdragonhead!, and some missing heads.

### ISSUE THREAD

**Issue by leasoncre** [cnaude/TrophyHeads#4]
1. Can you please have the enderdragon drop be the new enderdragon head for servers running 1.9 instead of the old player-style head. (ITEM id: 397:5) i tried changing config to '@default', but it does not work.
2. missing 'horse' head
3. missing 'silverfish' head
4. missing 'irongolem' head
5. missing 'bat' head

i'm migrating to this plugin from playerheads because it isn't maintained anymore and has a minor bug that annoys me alot. found these missing heads by comparing configs. o.O

6. add an option/ability for players to right click a head and get a message saying who the head belongs too so they don't have to break the head to find out. (and if the head has no valid uuid/name say 'custom head', this is the main bug with player heads that bugs me)

thanks, great plugin!

**Comment by cnaude** [comment]
Please test this version. https://h.cnaude.org/jenkins/job/TrophyHeads/27/

**Comment by cnaude** [comment]
https://h.cnaude.org/jenkins/job/TrophyHeads/31/

**Comment by leasoncre** [comment]
NOTE: Updated my spigot version to: git-Spigot-3104eb1-68b7277 (MC: 1.9) (Implementing API version 1.9-R0.1-SNAPSHOT)

1. build 31, no heads drop. 
tested on pig, cow, chicken, blaze, zombie and skeleton to confirm. 
default config regenerated when build 31 installed.

build 29: (might have been fixed? can't check until drops are fixed)
2. heads don't take the color/skin of the head until placed (i think they should do so immediately)
3. when a head is broken after the first placement (survival) the head says "UNKNOWN" (found this out on a blaze head before i updated to b31)

4 status on making the ender dragon drop it's minecraft:skull:5 head?

**Comment by leasoncre** [comment]
[[edited above comment for more clarifications, should be done testing this for the moment]]

**Comment by leasoncre** [comment]
would it be possible to add the wither boss [head] as well? on the wiki it has white eyes instead of black http://minecraft.gamepedia.com/Mob

**Comment by leasoncre** [comment]
@4 enderdragon dropped it's head! (1.9 default minecraft head)

6. wither skeleton mobs don't drop heads
7. the 5 horse types drop differently named heads, but all have the same skin, should they be different? [Donkey, Horse, Mule, Skeleton, Zombie]

**Comment by cnaude** [comment]
If you can find skin accounts for all of the different horse types I will add them.
I'm in the process of fixing the left click and adding right click.
Thanks for testing.

**Comment by leasoncre** [comment]
well.. brilliant.. i still had playerheads installed when i tested those heads...

**Comment by cnaude** [comment]
Go ahead and try latest build. https://h.cnaude.org/jenkins/job/TrophyHeads/34/

**Comment by leasoncre** [comment]
@ 1 . not verified fixed
@ 2 . assume fixed or invalid
@ 3 . heads retain their custom name now. 
-Why are they green text? (not that it really matters)
-why does the guardian head say 'ELDER_GUARDIAN Head'(Green Text) ?  it should say 'Guardian Head'
-[ps: will the elder guardian drop a custom head as well or the same as a regular guardian?, just tried, elder guardian drops the same head, but name is 'Elder Guardian Head'(White Italic Text)] (i'm fine with them dropping the same head)
@ 4 . fixed
5 . message is printed twice. 
-and the mob name is a different color for each mob, intended?
-enderdragon skull registers as 'unknown'
6 . wither skeletons still don't drop heads at all, [needs to be fixed or making-beacons/summoning-the-wither will be impossible.
@ 7 . not implimenting

**Comment by cnaude** [comment]
The Elder Guardian should display correctly with latest build and setting the "skin: ElderGuardian".
Wither Skeletons now drop heads.
And Dragon skulls now display info correctly on right click.
I'm still working on the double message issue. I think it's a bug in the Minecraft client, but I'm still researching it.
The different colors are intentional. Of course you can change any message you like. If you have an idea for better colors or messages let me know and Ill change the defaults.

**Comment by cnaude** [comment]
Latest build is https://h.cnaude.org/jenkins/job/TrophyHeads/37/

**Comment by leasoncre** [comment]
[Note: loaded from scratch, config regenerated]
1 .  not fixed on first load. (have to run plugin twice before heads drop)

5 . message printed twice

!5b . assuming you also changed something to where it doesn't use the message in the config file (per head). a lot of the heads now say the username of the head instead of just ie:'bat' and they all have the same color name(biggest clue) (yellow)
i liked how it was previously with the custom message per-head :) NOTE: this is a problem related to # 1 !


5c . message works (double print) when _sneaking_ both left and right click. (recommend removing sneak check if it's still in there)

6 . fixed, PS. whats the default drop rate of wither skeleton heads?

8 . recommend changing the config name of 'sneak-punch-info' and no break as it's now using right click event. 

9. any custom head (not using a username) causes an error on lookup in console. i'd prefer a message to be printed to the user saying 'That is a Custom head!' ..plus console errors are annoying and spammy. we use command-block-spawned-in heads on our server. IE commandblock: /give @p skull 1 3 {display:{Name:"Podzol"},SkullOwner:{Id:"27743c84-c5fa-4334-848b-c2fd293f23f8",Properties:{textures:[{Value:"eyJ0aW1lc3RhbXAiOjE0MTE1ODEzNTgwMjAsInByb2ZpbGVJZCI6ImRiM2RkNDEyMzBiOTRkMGU4NWNhNThmMGYzMjQ5NmRkIiwicHJvZmlsZU5hbWUiOiJQaGFzZVB2UCIsInRleHR1cmVzIjp7IlNLSU4iOnsidXJsIjoiaHR0cDovL3RleHR1cmVzLm1pbmVjcmFmdC5uZXQvdGV4dHVyZS9hNDE5NWY5YTQzOWM2ZDBmZmQxOTYxNjU3ZjZmMGFhOGUzYTJmOGEyNDkzYWZhNjYyYWI1ZTQxOTNlMCJ9fX0="}]}}}

[01:52:44] [Server thread/ERROR]: Could not pass event PlayerInteractEvent to TrophyHeads v1.12.7-37
org.bukkit.event.EventException
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:310) ~[spigot-1.9.jar:git-Spigot-3104eb1-68b7277]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[spigot-1.9.jar:git-Spigot-3104eb1-68b7277]
	at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:502) [spigot-1.9.jar:git-Spigot-3104eb1-68b7277]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:487) [spigot-1.9.jar:git-Spigot-3104eb1-68b7277]
	at org.bukkit.craftbukkit.v1_9_R1.event.CraftEventFactory.callPlayerInteractEvent(CraftEventFactory.java:227) [spigot-1.9.jar:git-Spigot-3104eb1-68b7277]
	at net.minecraft.server.v1_9_R1.PlayerInteractManager.a(PlayerInteractManager.java:482) [spigot-1.9.jar:git-Spigot-3104eb1-68b7277]
	at net.minecraft.server.v1_9_R1.PlayerConnection.a(PlayerConnection.java:880) [spigot-1.9.jar:git-Spigot-3104eb1-68b7277]
	at net.minecraft.server.v1_9_R1.PacketPlayInUseItem.a(SourceFile:55) [spigot-1.9.jar:git-Spigot-3104eb1-68b7277]
	at net.minecraft.server.v1_9_R1.PacketPlayInUseItem.a(SourceFile:11) [spigot-1.9.jar:git-Spigot-3104eb1-68b7277]
	at net.minecraft.server.v1_9_R1.PlayerConnectionUtils$1.run(SourceFile:13) [spigot-1.9.jar:git-Spigot-3104eb1-68b7277]
	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) [?:1.8.0_74]
	at java.util.concurrent.FutureTask.run(Unknown Source) [?:1.8.0_74]
	at net.minecraft.server.v1_9_R1.SystemUtils.a(SourceFile:45) [spigot-1.9.jar:git-Spigot-3104eb1-68b7277]
	at net.minecraft.server.v1_9_R1.MinecraftServer.D(MinecraftServer.java:721) [spigot-1.9.jar:git-Spigot-3104eb1-68b7277]
	at net.minecraft.server.v1_9_R1.DedicatedServer.D(DedicatedServer.java:400) [spigot-1.9.jar:git-Spigot-3104eb1-68b7277]
	at net.minecraft.server.v1_9_R1.MinecraftServer.C(MinecraftServer.java:660) [spigot-1.9.jar:git-Spigot-3104eb1-68b7277]
	at net.minecraft.server.v1_9_R1.MinecraftServer.run(MinecraftServer.java:559) [spigot-1.9.jar:git-Spigot-3104eb1-68b7277]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_74]
Caused by: java.lang.NullPointerException
	at java.util.concurrent.ConcurrentHashMap.containsValue(Unknown Source) ~[?:1.8.0_74]
	at com.cnaude.trophyheads.CaseInsensitiveMap.containsValue(CaseInsensitiveMap.java:391) ~[?:?]
	at com.cnaude.trophyheads.TrophyHeads.onPlayerInteractEvent(TrophyHeads.java:179) ~[?:?]
	at sun.reflect.GeneratedMethodAccessor154.invoke(Unknown Source) ~[?:?]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_74]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_74]
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:306) ~[spigot-1.9.jar:git-Spigot-3104eb1-68b7277]
	... 17 more

Attached personnel recommended colors/names for mob messages (config file)
[config.txt](https://github.com/cnaude/TrophyHeads/files/166627/config.txt)

Top notch support!

**Comment by leasoncre** [comment]
5d .  Guardians and Elder_Guardians are (right click) reported as 'Guardian'
- Wither_Skeleton, and Wither skulls are (right click) reported as 'Wither Boss

**Comment by cnaude** [comment]
I think build 42 is working very nicely. https://h.cnaude.org/jenkins/job/TrophyHeads/42/

**Comment by leasoncre** [comment]
@ 1 . fixed.
@ 5 . fixed.
@5b . fixed by # 1
@5c . (removed unneeded code, check)
@5d . Fixed. (had to get a fresh head)
@ 8 . fixed/changed
@ 9 . fixed.
--all previous bugs fixed--

minor config grammar fixes/changes:
'&eThis head once belonged to an &3Elder Guardian&e.' @fixed: 'a elder guardian'
'&eThis head once belonged to an &5Endermite&e.' @fixed: 'a endermite'
'&eThis head once belonged to a &fSnow Golem&e.' @fixed: 'an snow golem'
'&eThis head once belonged to a &5Witch&e.' @fixed: 'an witch'

1 . minor bug: not important to fix: when the head ropps, it doesn't take the new skin until picked up
2 . minor bug: custom(Trophy Heads) heads with custom names don't keep their custom names when placed and re-mined. IE: horse mob types:'donkey','mule','skeleton horse','zombie horse', 'killer bunny' drop their head with custom name, but lose it on placement in-world.
-this includes heads renamed in an anvil and placed/re-mined. (not expecting this to get fixed)
3 . not important: 'Giant' mob doesn't drop a head (i really don't care if it does, it'll never be used)

should be ready for release version :)

**Comment by leasoncre** [comment]
1.8.8 testing for backwards compatability:
add backwards compatibility for 1.8? detect minecraft version on startup and use player enderdragon skull? or just tell players to change the config?
--nothing else found--

**Comment by leasoncre** [comment]
add a message & config option for pvp beheadings: **(overrides the default 'player was killed by player2' message)**

config options example:
```
##makes all beheadings broadcast only the generic message, regardless of death type [default=false]
broadcast-all-generic: false 
##TRUE: broadcast message uses players displayname/rank/title. FALSE: broadcast msg uses  usernames (plainer message) [default=true] 
use-displayname: true 

broadcast-msg-pvp: '&c%%NAME%%&e was beheaded by &e&c%%NAME2%%&e'
broadcast-pvp: true
broadcast-msg-generic: &c%%NAME%%&e was beheaded!
broadcast-generic: true
broadcast-msg-self: &c%%NAME%%&e beheaded themselves. o.O
broadcast-self: true
```

**Comment by leasoncre** [comment]
git-Spigot-23e921f-8b69bdd (MC: 1.9) (Implementing API version 1.9-R0.1-SNAPSHOT)
TrophyHeads version 1.12.7-43

---------------
custom head message event fired twice.

**Comment by cnaude** [comment]
What's happening is when a player performs a right click the client sends the event to the server twice. The Spigot API then forwards the event to the plugin twice. I have some code that adds a cool down. It's probable that the cooldown was not long enough. I'll increase the cooldown.

**Comment by leasoncre** [comment]
it was only the custom head though, none of the others

**Comment by leasoncre** [comment]
been busy?

**Comment by cnaude** [comment]
Yup. I might have some free time later tonight.

**Comment by cnaude** [comment]
For the right click issue try https://h.cnaude.org/jenkins/job/TrophyHeads/44/

**Comment by leasoncre** [comment]
did you add the cooldown code to the null(custom/cmdblk) head message code? (i'd assume it's different from the rest of the heads, as it's more of an error than a ligit head)
as it doesn't matter what i set the cool down too, it's ignored for the custom heads

**Comment by cnaude** [comment]
You are absolutely correct. The custom head check was bypassing the cooldown timer.
